### ISSUE TITLE
Create VSCode Extension Boiler Plate Code

### ISSUE THREAD

**Issue by NLaundry** [Intelligent-Adaptive-Interventions-Lab/I-AI-CoLab-Creation-VSCode-Extension#1]

**Comment by steventohme** [comment]
hey @Intelligent-Adaptive-Interventions-Lab/instructor-ai-colab. I made a startup guide to creating a VSCode extension. Let me know if I should make any changes. Once we figure out what we're calling the extension i'll upload the boiler plate code to the repo.
[extensionStartup.md](https://github.com/Intelligent-Adaptive-Interventions-Lab/I-AI-CoLab-Creation-VSCode-Extension/files/11278130/extensionStartup.md)
